### PR TITLE
Fix toolbar

### PR DESCRIPTION
**Pull request by damanpreetsb**
Fix filter by grow zone status and fix toolbar title position when items in toolbar shown

### CODE REVIEW

**Comment by damanpreetsb** [comment]
> @googlebot I signed it!

**Comment by damanpreetsb** [comment]
> @googlebot I fixed it.

**Comment by tiembo** [comment]
Thanks for the PR!  Can you rebase to master?

**Comment by damanpreetsb** [comment]
Hi, I have resolved the conflicts.

**Comment by damanpreetsb** [comment]
Hi @tiembo , Any updates regarding this?

**Comment by tiembo** [comment]
Hi @damanpreetsb, sorry for the delay.  Some comments:

* the filter checkbox state can be inconsistent.  For example, check the grow zone box, go to My Garden, and then back to Plant List.  The list of plants are still filtered but the checkbox is unchecked
* prefer to have the filter icon showing versus an overflow menu

**Pull request closed without merging**
