### PR TITLE
Add Progaurd to let app works on release mode #901

### LINKED ISSUE #901: [Bug]: Release build is not showing any data
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to the sample app?

- [X] Yes, this is a specific issue related to this samples repo.

### Video to explain 

https://github.com/android/sunflower/assets/30949634/c6aca2cd-b248-4322-8313-ed8095db3486

## 

### Issue Explaining

when I tried to build a release version for the Sunflower project builds fine but once I install the APK the app have no data, 
and this issue is a well-known issue if we set the isMinifyEnabled to true, the minification process is causing some code or resource references to be removed or obfuscated.

When isMinifyEnabled is enabled in your app's build configuration, it enables code and resource shrinking through ProGuard or R8 (depending on your build system). This process analyzes your app's code and resources to remove unused code and optimize the resulting APK size.

### Some solutions to take into consideration: 

1.  Data classes or models: If you have data classes or models that are not being used directly in your code but are populated dynamically through reflection or serialization libraries, they may be removed by minification. To prevent this, you can add @Keep annotations to your data classes or model classes to instruct the minified to retain them. 

2. Reflection and dynamic code: If your app relies heavily on reflection or dynamically loading code, minification can interfere with the necessary references. To preserve such code, you can use ProGuard/R8 rules to specify the classes or methods that should not be removed or obfuscated.

## 

Part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

### Relevant logcat output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by qamarelsafadi**
## What?

Fixes #901 

## Why?

This pull request addresses the issue of not showing any data when we use a Release build, which is due to MinifyEnabling that works with Jetpack Compose 

## How?

To solve this issue we need to add a few rules on our Progaurd file to keep our classes not being minification,
I had to add new rules on the Progaurd file for Gson, and Retrofit as they mentioned that on their documentation, 
 and for our other classes, 

after adding the new rules everything works like a charm 🚀! 

https://github.com/android/sunflower/assets/30949634/c7168dd9-8445-4c28-bb7b-b29e14dcc569

## 

This PR is part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

### CODE REVIEW

**Review by arriolac — APPROVED** [review]
Thanks!

**Comment by vijay81** [comment]
Why Filter icon repeat in dashboard?

**Comment by qamarelsafadi** [comment]
> Why Filter icon repeat in dashboard?

Not from My code, seems like another pr was merged to the main before mine caused this issue to return.

**Comment by arriolac** [comment]
> Why Filter icon repeat in dashboard?

I don't see that issue in `main`. Please file an issue with repro steps.

**Pull request merged**
