### PR TITLE
Remove kotlin stdlib dependency

### PR DESCRIPTION
**Pull request by skydoves**
The stdlib library – starting from Kotlin 1.4.0, the stdlib dependency is added automatically.

### [Dependency on the standard library added by default](https://kotlinlang.org/docs/reference/whatsnew14.html#dependency-on-the-standard-library-added-by-default)
You no longer need to declare a dependency on the stdlib library in any Kotlin Gradle project, including a multiplatform one. The dependency is added by default.

### Difference
- [x] Removed a kotlin stdlib dependency in the `app` module.

### CODE REVIEW

**Review by nic0lette — CHANGES_REQUESTED** [review]
Thanks. I think that this is pretty straight forward, but I think that if we are removing the `implementation` line we should also remove the variable definition from the top level [`build.gradle` file](https://github.com/android/sunflower/blob/87873648ec7cc24a6a4ddb540b786041cde09d22/build.gradle#L36).

**Comment by skydoves** [comment]
Hi @nic0lette! Thanks for your PR review. 🙏
The `kotlinVersion` variable definition is also used in [kotlin-plugin](https://github.com/android/sunflower/blob/87873648ec7cc24a6a4ddb540b786041cde09d22/build.gradle#L62).

**Review by tiembo — APPROVED** [review]

**Review by nic0lette — APPROVED** [review]
You're right. Oops! Thank you!

**Comment by tiembo** [comment]
Thanks @skydoves and @nic0lette !

**Pull request merged**
