### PR TITLE
updated all most all the dependencies and some minor changes to to make the app work again 

### PR DESCRIPTION
**Pull request by braghome**
…g, espresso, fragment, glide, gson, hilt, junit, ktx, lifecycle, material, navigation, paging, recycler, room, truth, testExt, and work

2) remove lifecycle-extensions in favour of lifecycle-runtime-ktx
3) remove deprecated import on observe
4) update gradle version
5) add progard for gson update
6) fix unimplemented method error

### CODE REVIEW

**Comment by braghome** [comment]
@googlebot I signed it!

**Comment by calren** [comment]
@braghome Thanks for proactively updating the dependencies! 

From what I can tell, the app is working fine without the dependency updates though. Were there errors you faced without these updates? We generally try to make incremental updates to ensure nothing breaks.

**Comment by braghome** [comment]
@calren I did get compilation error when I updated the son version, the progard changes are the recommendations from gson release notes.

**Comment by arriolac** [comment]
No longer valid since migrating fully in Compose.

**Pull request closed without merging**
