### PR TITLE
👌 IMPROVE: updated plugin versions to stable (latest) versions

### PR DESCRIPTION
**Pull request by lionuncle**

### CODE REVIEW

**Comment by tiembo** [comment]
Thank you for the PR. Can you sign the CLA?

**Comment by lionuncle** [comment]
@googlebot I signed it!

**Comment by lionuncle** [comment]
> Thank you for the PR. Can you sign the CLA?

I signed the CLA

**Comment by arriolac** [comment]
This PR is outdated as dependencies have been upgraded (and some removed) since migrating Sunflower to Compose

**Pull request closed without merging**
