### PR TITLE
Implementation of Hilt

### PR DESCRIPTION
**Pull request by isfaaghyth**
For simplifying dependencies injection, I tried to replace the service allocator with Hilt 🚀

### CODE REVIEW

**Comment by isfaaghyth** [comment]
@googlebot I signed it!

**Comment by isfaaghyth** [comment]
hi @tiembo, I need your review, please

**Comment by manuelvicnt** [comment]
There's already a Hilt PR here #623

**Comment by isfaaghyth** [comment]
Hi @manuelvicnt, yes, I made this PR when I saw #623 had no changes in a month (there are no changes by your request), and seems #623 in a few commits using my code from here

**Comment by manuelvicnt** [comment]
That's because I've been busy and didn't have time to review that one. Planning to do so this week

**Comment by tiembo** [comment]
Thank you for this PR.  Hilt was merged in PR #623.

**Pull request closed without merging**
